from tkinter import *
import tkinter as tk
def show_frame(frame):
 frame.tkraise()
window=tk.Tk()
window.state('zoomed')
window.rowconfigure(0,weight=1)
window.columnconfigure(0,weight=1)
frame1=tk.Frame(window)
frame2=tk.Frame(window)
frame3=tk.Frame(window)
frame4=tk.Frame(window)
for frame in(frame1,frame2,frame3,frame4):
 frame1.grid(row=0,column=0,sticky='nsew')
 frame2.grid(row=0,column=0,sticky='nsew')
 frame3.grid(row=0,column=0,sticky='nsew')
 frame4.grid(row=0,column=0,sticky='nsew')
# FORM 1
frame4_title=tk.Label(frame4,text='COVID VACCINATION REGISTRATION AND STATUS',bg='BLUE')
frame4_title.pack(fill='x')
frame4_btn=tk.Button(frame4,text='verify',command=lambda:show_frame(frame3))
frame4_btn.pack()
label_0 =Label(frame4,text="REGISTER OR SIGNIN FOR VACCINATION",
width=40,font=("bold",20),bg='blue')
label_0.place(x=90,y=60)
label_1 =Label(frame4,text="USER NAME", width=20,font=("bold",10))
label_1.place(x=80,y=130)
entry_1=Entry(frame4)
entry_1.place(x=240,y=130)
label_3 =Label(frame4,text="PHONE NUMBER", width=20,font=("bold",10))
label_3.place(x=68,y=180)
entry_3=Entry(frame4)
entry_3.place(x=240,y=180)
# FORM 2
frame3_title=tk.Label(frame3,text='COVID VACCINATION REGRISTRATION AND STATUS',bg='blue')
frame3_title.pack(fill='x')
frame3_btn=tk.Button(frame3,text='back',command=lambda:show_frame(frame4))
frame3_btn.pack()
label_0 =Label(frame3,text="REGISTER FOR VACCINATION", width=30,font=("bold",20),bg='blue')
label_0.place(x=90,y=60)
label_1=Label(frame3,text="PHOTO ID PROOF",width=20,font=("bold",10))
label_1.place(x=80,y=130)
list_of_proof=[ 'Aadhaar Card','Driving License','PAN Card' ,'Passport' ,'Pension Passbook','NPR SmartCard','Voter ID']
c=StringVar()
droplist=OptionMenu(frame3,c, *list_of_proof)
droplist.config(width=15)
c.set('Select your proof')
droplist.place(x=240,y=130)
label_3 =Label(frame3,text="PHOTO ID NNUMBER", width=20,font=("bold",10))
label_3.place(x=68,y=180)
entry_3=Entry(frame3)
entry_3.place(x=240,y=180)
label_4 =Label(frame3,text="Gender", width=20,font=("bold",10))
label_4.place(x=70,y=230)
var=IntVar()
Radiobutton(frame3,text="Male",padx= 5, variable= var, value=1).place(x=235,y=230)
Radiobutton(frame3,text="Female",padx= 20, variable= var, value=2).place(x=290,y=230)
label_5=Label(frame3,text="FULL NAME",width=20,font=("bold",10))
label_5.place(x=70,y=280)
entry_5=Entry(frame3)
entry_5.place(x=240,y=280)
label_6=Label(frame3,text="DOSE",width=20,font=('bold',10))
label_6.place(x=75,y=330)
var1=IntVar()
Checkbutton(frame3,text="DOSE 1", variable=var1).place(x=230,y=330)
var2=IntVar()
Checkbutton(frame3,text="DOSE 2", variable=var2).place(x=290,y=330)
label_8 =Label(frame3,text="YEAR OF BIRTH", width=20,font=("bold",10))
label_8.place(x=80,y=390)
entry_8=Entry(frame3)
entry_8.place(x=250,y=390)
frame3_btn=tk.Button(frame3,text='register',command=lambda:show_frame(frame1))
frame3_btn.pack()
# FORM 3
frame1_title=tk.Label(frame1,text='COVID VACCINATION REGISTRATION AND STATUS',bg='blue')
frame1_title.pack(fill='x')
frame1_btn=tk.Button(frame1,text='back',command=lambda:show_frame(frame3))
frame1_btn.pack()
label_0 =Label(frame1,text="BOOK APPOINTMENT FOR VACCINATION",
width=35,font=("bold",20),bg='blue')
label_0.place(x=90,y=60)
label_1 =Label(frame1,text="ENTER THE PINCODE", width=20,font=("bold",10))
label_1.place(x=80,y=130)
entry_1=Entry(frame1)
entry_1.place(x=240,y=130)
label_3 =Label(frame1,text="DISTRICT", width=20,font=("bold",10))
label_3.place(x=68,y=180)
entry_3=Entry(frame1)
entry_3.place(x=240,y=180)
label_4 =Label(frame1,text="DOSE", width=20,font=("bold",10))
label_4.place(x=70,y=230)
var=IntVar()
Radiobutton(frame1,text="DOSE 1",padx= 5, variable= var, value=1).place(x=235,y=230)
Radiobutton(frame1,text="DOSE 2",padx= 20, variable= var, value=2).place(x=290,y=230)
label_5=Label(frame1,text="Country",width=20,font=("bold",10))
label_5.place(x=70,y=280)
list_of_country=[ 'India' ,'US' , 'UK' ,'Germany' ,'Austria']
c=StringVar()
droplist=OptionMenu(frame1,c, *list_of_country)
droplist.config(width=15)
c.set('Select your Country')
droplist.place(x=240,y=280)
label_6=Label(frame1,text="ADDRESS",width=20,font=('bold',10))
label_6.place(x=75,y=330)
var1=IntVar()
Checkbutton(frame1,text="GOVT HOSPITAL", variable=var1).place(x=230,y=330)
var2=IntVar()
Checkbutton(frame1,text="PRIVATE HOSPITAL", variable=var2).place(x=290,y=330)
frame1_btn=tk.Button(frame1,text='register',command=lambda:show_frame(frame2))
frame1_btn.pack()
#FORM 4
frame2_title=tk.Label(frame2,text='COVID VACCINATION REGISTRATION AND STATUS',bg='yellow')
frame2_title.pack(fill='x')
#frame2_btn=tk.Button(frame2,text='enter',command=lambda:show_frame(frame2))
#frame2_btn.pack()
#frame2_btn=tk.Button(frame2,text='submit',command=lambda:show_frame(frame3))
#frame2_btn.pack()
label_0 =Label(frame2,text="YOUR VACCINATION APPOINTMENT HAS BEEN SUCCESSFULLY BLOCKED",
width=70,font=("bold",20),bg='yellow')
label_0.place(x=100,y=100)
show_frame(frame1)
show_frame(frame2)
show_frame(frame3)
show_frame(frame4)
window.mainloop()
